/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopproject;

// User imports Afaq
import admin.Adminaccount;
import user.Account;
import user.User;

/**
 *
 * @author Afaq Qazi Taimoor Pervaiz
 */
public class gui extends javax.swing.JFrame {
    
    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MainTabbedPane = new javax.swing.JTabbedPane();
        userTabPanel = new javax.swing.JPanel();
        adminTabPanel = new javax.swing.JPanel();
        adminTabSidePanel = new javax.swing.JPanel();
        Adminpanelbutton = new javax.swing.JButton();
        InventorypanelButton = new javax.swing.JButton();
        adminAccountpanel = new javax.swing.JPanel();
        AdminLoginForm = new javax.swing.JPanel();
        AdminLoginFormLabel1 = new javax.swing.JLabel();
        AdminLoginFormLabel2 = new javax.swing.JLabel();
        AdminLoiginFormUsername = new javax.swing.JTextField();
        AdminLoginFormLabel3 = new javax.swing.JLabel();
        AdminLoginFormPassword = new javax.swing.JPasswordField();
        AdminLoginFormRegister = new javax.swing.JButton();
        AdminLoginFormLogin = new javax.swing.JButton();
        AdminLoginFormAlreadyRegistered = new javax.swing.JLabel();
        AdminLoginFormEmpty = new javax.swing.JLabel();
        AdminLoginFormRegistered = new javax.swing.JLabel();
        AdminLoginFormIncorrect = new javax.swing.JLabel();
        AdminLogoutButton = new javax.swing.JButton();
        adminInventorypanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTabPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        MainTabbedPane.addTab("User Tab", userTabPanel);

        adminTabPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminTabSidePanel.setBackground(new java.awt.Color(153, 153, 153));

        Adminpanelbutton.setText("Admin");
        Adminpanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminpanelbuttonActionPerformed(evt);
            }
        });

        InventorypanelButton.setText("Inventory");
        InventorypanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventorypanelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminTabSidePanelLayout = new javax.swing.GroupLayout(adminTabSidePanel);
        adminTabSidePanel.setLayout(adminTabSidePanelLayout);
        adminTabSidePanelLayout.setHorizontalGroup(
            adminTabSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTabSidePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(adminTabSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InventorypanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Adminpanelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        adminTabSidePanelLayout.setVerticalGroup(
            adminTabSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTabSidePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Adminpanelbutton)
                .addGap(53, 53, 53)
                .addComponent(InventorypanelButton)
                .addContainerGap(450, Short.MAX_VALUE))
        );

        adminTabPanel.add(adminTabSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        AdminLoginFormLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AdminLoginFormLabel1.setText("Enter Details to Login or Register");

        AdminLoginFormLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdminLoginFormLabel2.setText("Username");

        AdminLoiginFormUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoiginFormUsernameActionPerformed(evt);
            }
        });

        AdminLoginFormLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdminLoginFormLabel3.setText("Password");

        AdminLoginFormPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginFormPasswordActionPerformed(evt);
            }
        });

        AdminLoginFormRegister.setText("Register");
        AdminLoginFormRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginFormRegisterActionPerformed(evt);
            }
        });

        AdminLoginFormLogin.setText("Login");
        AdminLoginFormLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginFormLoginActionPerformed(evt);
            }
        });

        AdminLoginFormAlreadyRegistered.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AdminLoginFormAlreadyRegistered.setForeground(new java.awt.Color(204, 0, 0));
        AdminLoginFormAlreadyRegistered.setText("This user is already registered");

        AdminLoginFormEmpty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AdminLoginFormEmpty.setForeground(new java.awt.Color(204, 0, 0));
        AdminLoginFormEmpty.setText("The box can not be empty");

        AdminLoginFormRegistered.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AdminLoginFormRegistered.setForeground(new java.awt.Color(0, 204, 51));
        AdminLoginFormRegistered.setText("The user has been registered now");

        AdminLoginFormIncorrect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AdminLoginFormIncorrect.setForeground(new java.awt.Color(204, 0, 0));
        AdminLoginFormIncorrect.setText("Incorrect username or password");

        javax.swing.GroupLayout AdminLoginFormLayout = new javax.swing.GroupLayout(AdminLoginForm);
        AdminLoginForm.setLayout(AdminLoginFormLayout);
        AdminLoginFormLayout.setHorizontalGroup(
            AdminLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLoginFormLayout.createSequentialGroup()
                .addGroup(AdminLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminLoginFormLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(AdminLoginFormLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdminLoginFormLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(AdminLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AdminLoginFormLayout.createSequentialGroup()
                                .addComponent(AdminLoginFormRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AdminLoginFormLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AdminLoginFormEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminLoginFormAlreadyRegistered, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminLoginFormRegistered, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminLoginFormLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminLoginFormLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminLoiginFormUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AdminLoginFormPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AdminLoginFormIncorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        AdminLoginFormLayout.setVerticalGroup(
            AdminLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLoginFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminLoginFormLabel1)
                .addGap(31, 31, 31)
                .addComponent(AdminLoginFormLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminLoiginFormUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdminLoginFormLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminLoginFormPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdminLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminLoginFormRegister)
                    .addComponent(AdminLoginFormLogin))
                .addGap(18, 18, 18)
                .addComponent(AdminLoginFormEmpty)
                .addGap(18, 18, 18)
                .addComponent(AdminLoginFormIncorrect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminLoginFormAlreadyRegistered)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminLoginFormRegistered)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        AdminLogoutButton.setText("Logout");
        AdminLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminAccountpanelLayout = new javax.swing.GroupLayout(adminAccountpanel);
        adminAccountpanel.setLayout(adminAccountpanelLayout);
        adminAccountpanelLayout.setHorizontalGroup(
            adminAccountpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAccountpanelLayout.createSequentialGroup()
                .addGroup(adminAccountpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminAccountpanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(AdminLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminAccountpanelLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(AdminLogoutButton)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        adminAccountpanelLayout.setVerticalGroup(
            adminAccountpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAccountpanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(AdminLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(AdminLogoutButton)
                .addGap(37, 37, 37))
        );

        adminTabPanel.add(adminAccountpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 940, 450));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Inventory details");

        javax.swing.GroupLayout adminInventorypanelLayout = new javax.swing.GroupLayout(adminInventorypanel);
        adminInventorypanel.setLayout(adminInventorypanelLayout);
        adminInventorypanelLayout.setHorizontalGroup(
            adminInventorypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminInventorypanelLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(550, Short.MAX_VALUE))
        );
        adminInventorypanelLayout.setVerticalGroup(
            adminInventorypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminInventorypanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
        );

        adminTabPanel.add(adminInventorypanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MainTabbedPane.addTab("Admin Tab", adminTabPanel);

        getContentPane().add(MainTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
            //Admin functions
    private void AdminpanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminpanelbuttonActionPerformed
        // TODO add your handling code here:
                Adminaccount.ClearErrors(this.AdminLoginFormEmpty,this.AdminLoginFormAlreadyRegistered,this.AdminLoginFormRegistered,this.AdminLoginFormIncorrect);
        Adminaccount.show(this.AdminLoginForm, this.AdminLogoutButton);
        this.adminAccountpanel.setVisible(true);
        this.adminInventorypanel.setVisible(false);
        
        
    }//GEN-LAST:event_AdminpanelbuttonActionPerformed
        
    private void InventorypanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventorypanelButtonActionPerformed
        // TODO add your handling code here:
        this.adminAccountpanel.setVisible(false);
        this.adminInventorypanel.setVisible(true);
    }//GEN-LAST:event_InventorypanelButtonActionPerformed

    private void AdminLoiginFormUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoiginFormUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminLoiginFormUsernameActionPerformed

    private void AdminLoginFormRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginFormRegisterActionPerformed
        // TODO add your handling code here:
    Adminaccount.ClearErrors(this.AdminLoginFormEmpty,this.AdminLoginFormAlreadyRegistered,this.AdminLoginFormRegistered,this.AdminLoginFormIncorrect);
    String username = this.AdminLoiginFormUsername.getText();
    String password = this.AdminLoginFormPassword.getText();
    Adminaccount.registerAdmin(username,password,AdminLoginFormEmpty, AdminLoginFormAlreadyRegistered, AdminLoginFormRegistered);
    }//GEN-LAST:event_AdminLoginFormRegisterActionPerformed

    private void AdminLoginFormLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginFormLoginActionPerformed
        // TODO add your handling code here:
      Adminaccount.ClearErrors(this.AdminLoginFormEmpty,this.AdminLoginFormAlreadyRegistered,this.AdminLoginFormRegistered,this.AdminLoginFormIncorrect);
    String username = this.AdminLoiginFormUsername.getText();
    String password = this.AdminLoginFormPassword.getText();
    Adminaccount.loginAdmin(username, password, AdminLoginFormEmpty, AdminLoginFormIncorrect);
    Adminaccount.show(this.AdminLoginForm,this.AdminLogoutButton);
    }//GEN-LAST:event_AdminLoginFormLoginActionPerformed

    private void AdminLoginFormPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginFormPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminLoginFormPasswordActionPerformed

    private void AdminLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLogoutButtonActionPerformed
        // TODO add your handling code here:
        Adminaccount.logoutAdmin();
        Adminaccount.show(AdminLoginForm, AdminLogoutButton);
    }//GEN-LAST:event_AdminLogoutButtonActionPerformed

   
    // USER ACTION FUNCTON END
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gui a = new gui();
                a.setVisible(true);
                // this is so user does not see the account panel when he is not logged in
                a.userTabPanel.setVisible(false);
                a.adminAccountpanel.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminLoginForm;
    private javax.swing.JLabel AdminLoginFormAlreadyRegistered;
    private javax.swing.JLabel AdminLoginFormEmpty;
    private javax.swing.JLabel AdminLoginFormIncorrect;
    private javax.swing.JLabel AdminLoginFormLabel1;
    private javax.swing.JLabel AdminLoginFormLabel2;
    private javax.swing.JLabel AdminLoginFormLabel3;
    private javax.swing.JButton AdminLoginFormLogin;
    private javax.swing.JPasswordField AdminLoginFormPassword;
    private javax.swing.JButton AdminLoginFormRegister;
    private javax.swing.JLabel AdminLoginFormRegistered;
    private javax.swing.JButton AdminLogoutButton;
    private javax.swing.JTextField AdminLoiginFormUsername;
    private javax.swing.JButton Adminpanelbutton;
    private javax.swing.JButton InventorypanelButton;
    private javax.swing.JTabbedPane MainTabbedPane;
    private javax.swing.JPanel adminAccountpanel;
    private javax.swing.JPanel adminInventorypanel;
    private javax.swing.JPanel adminTabPanel;
    private javax.swing.JPanel adminTabSidePanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel userTabPanel;
    // End of variables declaration//GEN-END:variables
}
